FROM thecodingmachine/php:8.2-v4-apache-node16

USER root
RUN apt-get update && apt-get install -y make jq

RUN wget -q https://phar.phpunit.de/phpcov.phar && \
    chmod a+x phpcov.phar && \
    mv phpcov.phar /usr/bin/phpcov

USER docker
